{{- if .Values.enableCodeAgent }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.scmType}}-code-agent-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ca
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-ca
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-ca
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "snyk-broker.serviceAccountName" . }}-{{ .Release.Name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: code-agent
          resources:
            limits:
              cpu: {{ .Values.caResources.limits.cpu }}
              memory: {{ .Values.caResources.limits.memory }}
            requests:
              cpu: {{ .Values.caResources.requests.cpu }}
              memory: {{ .Values.caResources.requests.memory}}
          securityContext:
            {{- toYaml .Values.securityContextCa | nindent 12 }}
          image: "{{ .Values.image.caRepository }}:{{ .Values.caImage}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.caSnykPort }}
          env:
            - name: PORT
              value: {{ .Values.deployment.container.caSnykPort | squote }}
            {{- if .Values.upstreamUrlCodeAgent }}
            - name: UPSTREAM_URL
              value:  {{ .Values.upstreamUrlCodeAgent | squote }}
            {{- end }}
            - name: SNYK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: snyk-token
                  key: snyk-token-key
         {{- if .Values.tlsRejectUnauthorized  }}
         # Troubleshooting - Set to 0 for SSL inspection testing
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
         {{- end }}
         {{- if .Values.httpsProxy }}
         # HTTPS Proxy Settings
            - name: HTTPS_PROXY
              value: {{ .Values.httpsProxy }}
         {{- end }}
         {{- range .Values.env }}
         # custom env var in override.yaml
            - name: {{ .name }}
              value: {{ .value | squote }} 
        {{- end}}
        
---                     
apiVersion: v1
kind: Service
metadata:
  name: "code-agent-service-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.caType }}
  ports:
    - port: {{ .Values.deployment.container.caSnykPort }}
      targetPort: {{ .Values.deployment.container.caSnykPort}}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-ca
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- end }}
